import './style.css'
import { createSupportRequest, isSupabaseConfigured } from './supabase.js'

const deals = [
  { id: 'DL-24019', name: 'OO기업 Cloud 전환', customer: 'OO기업', owner: '박지훈', engineer: '김서연', status: '제안 준비', region: '수도권', product: 'Cloud Infrastructure', value: '₩420M', updated: '오늘 09:24', progress: 68, accent: 'mint' },
  { id: 'DL-24018', name: '한빛제조 데이터센터 현대화', customer: '한빛제조', owner: '이수민', engineer: '최도윤', status: '고객 미팅 예정', region: '충청', product: 'Hybrid Cloud', value: '₩280M', updated: '어제 16:10', progress: 42, accent: 'blue' },
  { id: 'DL-24016', name: '에버웍스 백업 아키텍처', customer: '에버웍스', owner: '정하늘', engineer: '김서연', status: '기술검토', region: '영남', product: 'Backup & DR', value: '₩95M', updated: '09/15 13:50', progress: 31, accent: 'purple' },
  { id: 'DL-24012', name: '세림금융 Private Cloud 구축', customer: '세림금융', owner: '박지훈', engineer: '윤현우', status: '수주', region: '수도권', product: 'Private Cloud', value: '₩610M', updated: '09/12 10:05', progress: 100, accent: 'orange' },
  { id: 'DL-24009', name: '동해물산 DR 컨설팅', customer: '동해물산', owner: '김유진', engineer: '최도윤', status: '일정 조율', region: '영남', product: 'Backup & DR', value: '₩72M', updated: '09/10 11:22', progress: 19, accent: 'blue' }
]

const nav = [
  ['dashboard', '⌂', 'Dashboard'], ['requests', '＋', '기술지원 요청'], ['deals', '▣', 'Deal 관리'], ['calendar', '◷', '일정'], ['docs', '▤', '문서 / 산출물'], ['productivity', '◒', '생산성']
]
let active = 'dashboard'

const app = document.querySelector('#app')
function statusClass(status) { return ({ '제안 준비':'status-mint','고객 미팅 예정':'status-blue','기술검토':'status-purple','수주':'status-green','일정 조율':'status-orange' })[status] || 'status-gray' }
function iconLabel(icon, text) { return `<span class="nav-icon">${icon}</span><span>${text}</span>` }

function render() {
  app.innerHTML = `<div class="shell">
    <aside class="sidebar"><div class="brand"><div class="brand-mark">✓</div><div><strong>dealflow</strong><small>SUPPORT OPERATIONS</small></div></div>
      <div class="workspace"><span class="workspace-dot"></span><div><b>SA Operations</b><small>내부 업무 포털</small></div><span class="chevron">⌄</span></div>
      <nav>${nav.map(([id,ic,label]) => `<button class="nav-item ${active===id?'active':''}" data-nav="${id}">${iconLabel(ic,label)}${id==='requests'?'<span class="nav-count">4</span>':''}</button>`).join('')}</nav>
      <div class="sidebar-bottom"><button class="nav-item" data-nav="settings">⚙ <span>설정</span></button><div class="profile"><div class="avatar">김</div><div><b>김서연</b><small>기술지원 담당자</small></div><span>•••</span></div></div>
    </aside>
    <main class="main"><header><div class="crumb">SA Operations <span>/</span> ${active === 'dashboard' ? 'Dashboard' : nav.find(n=>n[0]===active)?.[2] || 'Dashboard'}</div><div class="header-actions"><button class="icon-btn">⌕</button><button class="icon-btn notification">♢<i></i></button><button class="help">?</button></div></header>${active==='dashboard'?dashboard():active==='deals'?dealList():genericPage(active)}</main>
  </div>${requestModal()}`
  bind()
}

function dashboard() { return `<section class="content"><div class="welcome-row"><div><p class="eyebrow">THURSDAY, SEPTEMBER 17, 2026</p><h1>좋은 아침이에요, 서연님 <span>✦</span></h1><p class="subtext">오늘도 고객의 다음 가능성을 함께 만들어보세요.</p></div><button class="primary" id="new-request">＋ 기술지원 요청</button></div>
  <div class="metric-grid"><div class="metric"><div class="metric-top"><span>내 Main Deal</span><span class="metric-icon mint-bg">↗</span></div><strong>8</strong><small class="trend up">↑ 2 <em>지난달 대비</em></small></div><div class="metric"><div class="metric-top"><span>일정 선택 필요</span><span class="metric-icon blue-bg">◷</span></div><strong>3</strong><small class="trend warn">확인이 필요해요</small></div><div class="metric"><div class="metric-top"><span>이번 주 미팅</span><span class="metric-icon purple-bg">▣</span></div><strong>5</strong><small class="trend"><em>다음 미팅까지</em> 2일</small></div><div class="metric"><div class="metric-top"><span>진행 중 Deal</span><span class="metric-icon orange-bg">◒</span></div><strong>14</strong><small class="trend up">↑ 12% <em>팀 전체</em></small></div></div>
  <div class="grid-two"><div class="card activity-card"><div class="card-head"><div><h2>최근 활동</h2><p>담당 Deal에서 일어난 변화예요.</p></div><button class="text-btn">전체 보기 →</button></div><div class="activity-list">${[['mint','김서연님이 제안서 초안을 업로드했어요.','OO기업 Cloud 전환','오늘 09:24'],['blue','새로운 기술지원 요청이 도착했어요.','한빛제조 데이터센터 현대화','어제 16:10'],['purple','미팅 일정이 확정되었어요.','세림금융 Private Cloud 구축','어제 11:32'],['orange','Deal 상태가 변경되었어요.','에버웍스 백업 아키텍처','09/15 13:50']].map(a=>`<div class="activity"><span class="activity-dot ${a[0]}"></span><div><b>${a[1]}</b><small>${a[2]}</small></div><time>${a[3]}</time></div>`).join('')}</div></div><div class="card capacity"><div class="card-head"><div><h2>팀 업무량</h2><p>현재 진행 중인 Deal 기준</p></div><button class="more">•••</button></div><div class="capacity-main"><div class="donut"><div><strong>32</strong><small>진행 Deal</small></div></div><div class="legend"><span><i class="dot main-dot"></i>Main <b>18</b></span><span><i class="dot sub-dot"></i>Sub <b>14</b></span><span><i class="dot done-dot"></i>완료 <b>24</b></span></div></div><button class="outline full" data-nav="productivity">팀 Dashboard 보기</button></div></div>
  <div class="card deal-card"><div class="card-head"><div><h2>내 Deal 현황</h2><p>최근 업데이트 순으로 보여드려요.</p></div><div class="card-actions"><button class="filter">필터 <span>⌄</span></button><button class="text-btn" data-nav="deals">전체 Deal 보기 →</button></div></div>${dealRows(deals.slice(0,4))}</div></section>` }

function dealRows(rows) { return `<div class="table-wrap"><table><thead><tr><th>DEAL</th><th>고객</th><th>담당자</th><th>상태</th><th>업데이트</th><th></th></tr></thead><tbody>${rows.map(d=>`<tr class="deal-row" data-deal="${d.id}"><td><div class="deal-name"><span class="deal-accent ${d.accent}"></span><div><b>${d.name}</b><small>${d.id} · ${d.product}</small></div></div></td><td>${d.customer}</td><td><span class="mini-avatar">${d.engineer.slice(0,1)}</span>${d.engineer}</td><td><span class="status ${statusClass(d.status)}">${d.status}</span></td><td class="muted">${d.updated}</td><td class="row-arrow">→</td></tr>`).join('')}</tbody></table></div>` }

function dealList() { return `<section class="content"><div class="page-title"><div><p class="eyebrow">DEAL MANAGEMENT</p><h1>전체 Deal</h1><p class="subtext">기술지원이 연결된 모든 업무를 한 곳에서 관리하세요.</p></div><button class="primary" id="new-request">＋ 기술지원 요청</button></div><div class="toolbar"><div class="search">⌕ <input placeholder="고객사, Deal명, 담당자 검색" /></div><button class="filter">상태 <span>⌄</span></button><button class="filter">제품 <span>⌄</span></button><button class="filter">지역 <span>⌄</span></button></div><div class="card deal-card">${dealRows(deals)}</div></section>` }

function genericPage(id) { const info={requests:['기술지원 요청','새로운 요청을 확인하고 담당자를 배정하세요.','4건의 요청이 확인을 기다리고 있어요.'],calendar:['일정 조율','고객 미팅 후보와 확정 일정을 관리하세요.','이번 주 예정된 미팅 5건'],docs:['문서 / 산출물','Deal에 연결된 제안서와 기술자료를 한 곳에서 확인하세요.','최근 업로드 12건'],productivity:['생산성 Dashboard','평가가 아닌 리소스 배분을 위한 팀 업무량을 확인하세요.','팀 전체 진행 Deal 32건']}[id]||['설정','업무 환경을 관리합니다.','']; return `<section class="content"><div class="page-title"><div><p class="eyebrow">SA OPERATIONS</p><h1>${info[0]}</h1><p class="subtext">${info[1]}</p></div>${id==='requests'?'<button class="primary" id="new-request">＋ 요청 작성</button>':''}</div><div class="empty-panel"><div class="empty-orb">${id==='calendar'?'◷':id==='docs'?'▤':id==='productivity'?'◒':'＋'}</div><h2>${info[2]}</h2><p>이 화면은 Supabase 데이터가 연결되면 실제 업무 데이터로 채워집니다.</p>${id==='productivity'?'<div class="bars">'+[68,48,85,54,39,72].map((n,i)=>`<span style="height:${n}%"><em>${n}</em><small>${['김서연','최도윤','윤현우','박지훈','이수민','정하늘'][i]}</small></span>`).join('')+'</div>':''}</div></section>` }

function requestModal() { return `<div class="modal-backdrop" id="modal"><div class="modal"><div class="modal-head"><div><p class="eyebrow">NEW REQUEST</p><h2>기술지원 요청</h2><p>영업과 기술지원팀이 같은 화면에서 시작합니다.</p></div><button class="close" id="close">×</button></div><form id="request-form"><label>고객사<input name="customer" required placeholder="예: OO기업" /></label><label>Deal명<input name="deal" required placeholder="예: Cloud 전환 프로젝트" /></label><div class="form-grid"><label>제품 / 서비스<select name="product"><option>Cloud Infrastructure</option><option>Hybrid Cloud</option><option>Backup & DR</option></select></label><label>중요도<select name="priority"><option>높음</option><option>보통</option><option>낮음</option></select></label></div><label>기술지원 요청 내용<textarea name="description" required placeholder="고객 요구사항과 필요한 기술지원을 적어주세요."></textarea></label><label>예상 일정<input name="schedule" placeholder="예: 9월 마지막 주" /></label><div class="modal-foot"><span class="secure">▣ Supabase에 안전하게 저장됩니다</span><button type="button" class="outline" id="cancel">취소</button><button type="submit" class="primary">요청 등록하기</button></div></form></div></div>` }

function bind() { document.querySelectorAll('[data-nav]').forEach(b=>b.addEventListener('click',()=>{active=b.dataset.nav; render()})); document.querySelectorAll('.deal-row').forEach(r=>r.addEventListener('click',()=>showToast(`${r.dataset.deal} 상세 화면을 준비 중이에요.`))); document.querySelectorAll('#new-request').forEach(b=>b.addEventListener('click',()=>document.querySelector('#modal').classList.add('open'))); document.querySelector('#close')?.addEventListener('click',closeModal); document.querySelector('#cancel')?.addEventListener('click',closeModal); document.querySelector('#request-form')?.addEventListener('submit',async e=>{e.preventDefault(); const fd=new FormData(e.target); const result=await createSupportRequest({customer:fd.get('customer'),deal_name:fd.get('deal'),product:fd.get('product'),priority:fd.get('priority'),description:fd.get('description'),schedule:fd.get('schedule'),status:'submitted'}); closeModal(); showToast(result.demo||!isSupabaseConfigured?'요청이 등록됐어요. 팀장에게 알림을 보냈습니다.':'요청이 Supabase에 등록됐어요.'); }); }
function closeModal(){ document.querySelector('#modal')?.classList.remove('open') }
function showToast(message){ const t=document.createElement('div');t.className='toast';t.textContent=message;document.body.appendChild(t);setTimeout(()=>t.remove(),2800) }
render()
